version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -lc '
      python manage.py collectstatic --noinput || true;
      for i in {1..30}; do
        python manage.py migrate --noinput && break;
        echo "DB not ready, retrying ($i/30)..."; sleep 2;
      done;
      gunicorn easyparking.wsgi:application --bind 0.0.0.0:8080 --workers 3
      '
    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    ports:
      - "${WEB_PORT}:8080"  # expose เฉพาะพอร์ต 10079 เท่านั้น
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - pg_data:/var/lib/postgresql/data
    # ลบหรือไม่ระบุ `ports` หากไม่ต้องการ expose พอร์ต 5432
    # ports:
    #   - "${DB_PORT}:${DB_PORT}"

  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes"]
    # ลบหรือไม่ระบุ `ports` หากไม่ต้องการ expose Redis
    # ports:
    #   - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
