# Generated by Django 5.0.6 on 2025-01-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("easypark", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkinglocation",
            name="camera_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
