# Generated by Django 5.0.6 on 2025-01-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("easypark", "0002_parkinglocation_camera_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkinglocation",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="parking_images/"),
        ),
    ]
