# Generated by Django 5.0.6 on 2025-01-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("easypark", "0003_parkinglocation_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkingspot",
            name="x",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parkingspot",
            name="y",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
