# Generated by Django 5.0.6 on 2025-01-30 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("easypark", "0004_parkingspot_x_parkingspot_y"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkinglocation",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
