# Generated by Django 5.0.6 on 2025-01-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("easypark", "0005_parkinglocation_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "ผู้ใช้งานทั่วไป"),
                    ("admin", "ผู้ดูแลระบบ"),
                    ("manager", "เจ้าของลานจอดรถ"),
                ],
                default="user",
                max_length=10,
            ),
        ),
    ]
