# Generated by Django 5.0.6 on 2025-02-03 13:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("easypark", "0006_alter_customuser_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parkingspot",
            name="license_plate",
        ),
    ]
