# Generated by Django 5.0.6 on 2025-02-03 13:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("easypark", "0007_remove_parkingspot_license_plate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="created_at",
            new_name="completed_at",
        ),
        migrations.RemoveField(
            model_name="parkinglocation",
            name="camera_url",
        ),
        migrations.RemoveField(
            model_name="parkinglocation",
            name="description",
        ),
        migrations.RemoveField(
            model_name="parkinglocation",
            name="image",
        ),
        migrations.RemoveField(
            model_name="parkingspot",
            name="date",
        ),
        migrations.RemoveField(
            model_name="parkingspot",
            name="x",
        ),
        migrations.RemoveField(
            model_name="parkingspot",
            name="y",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="status",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="parkinglocation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservation_end_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservation_start_time",
            field=models.TimeField(),
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reservation_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("reservation_start_time", models.TimeField(default="08:00:00")),
                ("reservation_end_time", models.TimeField(default="12:00:00")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="easypark.parkinglocation",
                    ),
                ),
                (
                    "parking_spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="easypark.parkingspot",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
