# Generated by Django 5.0.6 on 2025-02-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("easypark", "0009_parkinglocation_camera_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkingspot",
            name="x",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parkingspot",
            name="y",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
