# Generated by Django 5.0.6 on 2025-02-07 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("easypark", "0010_parkingspot_x_parkingspot_y"),
    ]

    operations = [
        migrations.RenameField(
            model_name="parkingspot",
            old_name="x",
            new_name="x_position",
        ),
        migrations.RenameField(
            model_name="parkingspot",
            old_name="y",
            new_name="y_position",
        ),
    ]
