# Generated by Django 5.0.6 on 2025-02-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("easypark", "0011_rename_x_parkingspot_x_position_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingspot",
            name="x_position",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="parkingspot",
            name="y_position",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
