# Generated by Django 5.0.6 on 2025-02-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("easypark", "0013_alter_parkingspot_x_position_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkingspot",
            name="height",
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name="parkingspot",
            name="width",
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
