# Generated by Django 5.0.6 on 2025-02-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("easypark", "0014_parkingspot_height_parkingspot_width"),
    ]

    operations = [
        migrations.CreateModel(
            name="ROI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("x_position", models.FloatField()),
                ("y_position", models.FloatField()),
                ("width", models.FloatField()),
                ("height", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
