# Generated by Django 5.0.6 on 2025-02-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("easypark", "0016_roi_location_roi_parking_spot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingspot",
            name="spot_number",
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name="parkingspot",
            constraint=models.UniqueConstraint(
                fields=("location", "spot_number"), name="unique_spot_per_location"
            ),
        ),
    ]
