# Generated by Django 5.0.6 on 2025-03-01 03:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("easypark", "0017_alter_parkingspot_spot_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="reserved_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                    ("pending", "Pending"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
