# Generated by Django 5.0.6 on 2025-05-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("easypark", "0018_booking_reserved_at_alter_booking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkinglocation",
            name="floor",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
